language: python

install:
- pip install sphinx sphinx_rtd_theme

script:
- sphinx-build -Wv docs/source docs/html

deploy:
- provider: pages
  skip_cleanup: true
  keep-history: false
  github_token: $GH_TOKEN
  local_dir: docs/html
  on:
    branch: master
